name: Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build-release:
    name: Build Release APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Decode keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        echo $KEYSTORE_BASE64 | base64 -d > release.keystore
        
    - name: Update version
      if: github.event.inputs.version != ''
      run: |
        sed -i "s/versionName \"1.0\"/versionName \"${{ github.event.inputs.version }}\"/g" app/build.gradle
        
    - name: Build release APK
      run: ./gradlew assembleRelease
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        
    - name: Build release AAB
      run: ./gradlew bundleRelease
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        
    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk-${{ github.event.inputs.version || github.ref_name }}
        path: app/build/outputs/apk/release/*.apk
        retention-days: 365
        
    - name: Upload release AAB
      uses: actions/upload-artifact@v4
      with:
        name: release-aab-${{ github.event.inputs.version || github.ref_name }}
        path: app/build/outputs/bundle/release/*.aab
        retention-days: 365
        
    - name: Upload mapping file
      uses: actions/upload-artifact@v4
      with:
        name: mapping-file-${{ github.event.inputs.version || github.ref_name }}
        path: app/build/outputs/mapping/release/mapping.txt
        retention-days: 365
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this release
          - 音频播放器功能完整实现
          - 支持文件夹管理和多种播放模式
          - 后台播放和通知控制
          - 现代化UI设计和流畅动画
          
          ## 下载
          - APK文件: 在下方Artifacts中下载
          - AAB文件: 用于Google Play商店发布
          
          ## 安装说明
          1. 下载APK文件
          2. 在Android设备上允许"未知来源"安装
          3. 安装APK文件
          4. 授予存储权限
          5. 开始使用音频播放器
        draft: false
        prerelease: false